sebcom_homepage:
    path:     /
    defaults: { _controller: sebcomBundle:Default:index }
sebcom_show:
    path: /show
    defaults: { _controller: sebcomBundle:Default:show }
sebcom_authentification:
    path: /login
    defaults: { _controller: sebcomBundle:Default:login}