sebcom_homepage:
    path:     /
    defaults: { _controller: sebcomBundle:Default:index }
sebcom_show:
    path: /show
    defaults: { _controller: sebcomBundle:Default:show }
sebcom_authentification:
    path: /login
    defaults: { _controller: sebcomBundle:Default:login}
sebcom_menu:
    path: /menu
    defaults: { _controller: sebcomBundle:Default:menu}
sebcom_ajoutcat:
    path: /ajoutcat
    defaults: { _controller: sebcomBundle:Default:ajoutcat}
sebcom_modifiercat:
    path: /modifiercat/:id
    defaults: { _controller: sebcomBundle:Default:modifiercat}
sebcom_ajoutarticle:
    path: /ajoutarticle
    defaults: { _controller: sebcomBundle:Default:ajoutarticle}
sebcom_modifierarticle:
    path: /modifierarticle/:id
    defaults: { _controller: sebcomBundle:Default:modifierarticle}
sebcom_ajoutlivreur:
    path: /ajoutlivreur
    defaults: { _controller: sebcomBundle:Default:ajoutlivreur}
sebcom_modifierlivreur:
    path: /modifierlivreur/:id
    defaults: { _controller: sebcomBundle:Default:modifierlivreur}
sebcom_gestioncommande:
    path: /gestioncommande
    defaults: { _controller: sebcomBundle:Default:gestioncommande}
sebcom_promotion:
    path: /promotion
    defaults: { _controller: sebcomBundle:Default:promotion}
sebcom_modifierpromotion:
    path: /modifierpromotion/:id
    defaults: { _controller: sebcomBundle:Default:modifierpromotion}
sebcom_client:
    path: /home
    defaults: { _controller: sebcomBundle:Default:client}

    sebcom_ajoutclient:
        path: /signup
        defaults: { _controller: sebcomBundle:Default:ajoutclient}