sebcom_homepage:
    path:     /
    defaults: { _controller: sebcomBundle:Default:index }
sebcom_show:
    path: /show
    defaults: { _controller: sebcomBundle:Default:show }
sebcom_authentification:
    path: /login
    defaults: { _controller: sebcomBundle:Default:login}
sebcom_menu:
    path: /menu
    defaults: { _controller: sebcomBundle:Default:menu}
sebcom_ajoutcat:
    path: /ajoutcat
    defaults: { _controller: sebcomBundle:Default:ajoutcat}
sebcom_modifiercat:
    path: /modifiercat/:id
    defaults: { _controller: sebcomBundle:Default:modifiercat}
sebcom_ajoutarticle:
    path: /ajoutarticle
    defaults: { _controller: sebcomBundle:Default:ajoutarticle}



