sebcom:
    resource: "@sebcomBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
categorie_delete:
    path:     /ajoutcat/{id}
    defaults: { _controller: sebcomBundle:Default:deletecat }
categorie_modifier:
    path:     /modifiercat/{id}
    defaults: { _controller: sebcomBundle:Default:modifiercat }
article_delete:
    path:     /ajoutarticle/{id}
    defaults: { _controller: sebcomBundle:Default:deleteart }
article_modifier:
    path:     /modifierarticle/{id}
    defaults: { _controller: sebcomBundle:Default:modifierarticle }
livreur_delete:
    path:     /ajoutlivreur/{id}
    defaults: { _controller: sebcomBundle:Default:deletelivreur }
livreur_modifier:
    path:     /modifierlivreur/{id}
    defaults: { _controller: sebcomBundle:Default:modifierlivreur }
promotion_delete:
    path:     /promotion/{id}
    defaults: { _controller: sebcomBundle:Default:deletepromotion }
promotion_modifier:
    path:     /modifierpromotion/{id}
    defaults: { _controller: sebcomBundle:Default:modifierpromotion }
client_ajouter:
    path:     /signup
    defaults: { _controller: sebcomBundle:Default:ajoutclient }
    sebcom_listearticle  :
            path: /article
            defaults: { _controller: sebcomBundle:Default:listearticle}