sebcom:
    resource: "@sebcomBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
categorie_delete:
    path:     /ajoutcat/{id}
    defaults: { _controller: sebcomBundle:Default:deletecat }

delete:
    path:     /deleted
    defaults: { _controller: sebcomBundle:Default:deleted }

