sebcomBundle\Entity\sebcom\article:
    type: entity
    table: null
    repositoryClass: sebcomBundle\Repository\sebcom\articleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '55'
        description:
            type: string
            length: '55'
        prix:
            type: float
        image:
            type: string
            length: '200'
        quantite:
            type: integer
    lifecycleCallbacks: {  }
