sebcomBundle\Entity\sebcom\client:
    type: entity
    table: null
    repositoryClass: sebcomBundle\Repository\sebcom\clientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        login:
            type: string
            length: 255
        pass:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
