sebcomBundle\Entity\sebcom\commande:
    type: entity
    table: null
    repositoryClass: sebcomBundle\Repository\sebcom\commandeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        etat:
            type: string
            length: 255
        total:
            type: float
        prixliv:
            type: float
        dateliv:
            type: date
        idliv:
            type: integer
        idclient:
            type: integer
    lifecycleCallbacks: {  }
