<?php

namespace sebcomBundle\Repository\sebcom;

/**
 * compteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class compteRepository extends \Doctrine\ORM\EntityRepository
{
}
