<?php

namespace sebcomBundle\Repository\sebcom;

/**
 * livreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livreurRepository extends \Doctrine\ORM\EntityRepository
{
}
